spring:
  data:
    cassandra:
      keyspace-name: main
      username: <username>
      password: <password>
      schema-action: create_if_not_exists
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
      request:
        timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect.zip
astra.db:
  id: <dbid>
  region: us-east1
  keyspace: main
  application.token: <token>

